name: drugdiscovery
dependencies:
  - python=3.12
  - pip
  - pip:
    - docling
    - pandas 
    - numpy
    - unstructured-client
    - "unstructured[all-docs]"
    - watermark
    - tesserocr
    - python-Levenshtein
    - jiwer
    - plotly
    - openai
    - biopython
    - jupyterlab
    - biopython
    - metapub
    - pubmed-parser==0.3.1
    - requests
    - geotext
    - spacy
    - scispacy
    - elsapy==0.5.1

    
